In [3]:
"""
Simple exercises to get used to TensorFlow API
You should thoroughly test your code.
TensorFlow's official documentation should be your best friend here
CS20: "TensorFlow for Deep Learning Research"
cs20.stanford.edu
Created by Chip Huyen (chiphuyen@cs.stanford.edu)
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

sess = tf.InteractiveSession()
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################



###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

# YOUR CODE

###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

# YOUR CODE

###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

# YOUR CODE

###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

# YOUR CODE

###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

# YOUR CODE

###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

# YOUR CODE

-0.20894706


In [4]:
tf.reset_default_graph()
x = tf.random_uniform(shape=[], minval=-1, maxval=1, dtype=tf.float32)
y = tf.random_uniform(shape=[], minval=-1, maxval=1, dtype=tf.float32)
out = tf.case({x < y: (lambda: x+y),
               x > y: (lambda: x-y)},
              default=(lambda: 0.0))
with tf.Session() as sess:
    print(sess.run(out))

-1.8001301


In [8]:
x = [[0, 2, 1], [0, -1, -2]]
y = tf.zeros(shape=(2,3),dtype=tf.int32)
out = tf.equal(x, y)
with tf.Session() as sess:
    print(sess.run(out))

[[ True False False]
 [ True False False]]


In [15]:
x =[29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858]
out1 = tf.where(tf.greater(x, 30))
out2 = tf.gather(x, out1)
with tf.Session() as sess:
    print(sess.run([out1,out2]))

[array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 9],
       [11],
       [14],
       [16],
       [18]], dtype=int64), array([[31.190735],
       [30.97266 ],
       [38.084503],
       [34.944454],
       [34.45999 ],
       [36.01657 ],
       [30.20379 ],
       [33.711494],
       [36.055565]], dtype=float32)]


In [16]:
diag = tf.diag(tf.range(1,7))
with tf.Session() as sess:
    print(sess.run(diag))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [19]:
rand = tf.random_uniform(shape=(10,10))
det = tf.matrix_determinant(rand)
with tf.Session() as sess:
    print(sess.run([rand, det]))

[array([[0.08204412, 0.4617895 , 0.65314317, 0.35918808, 0.83899343,
        0.0683533 , 0.4634521 , 0.79272974, 0.15789092, 0.01455104],
       [0.10879493, 0.9301678 , 0.6100409 , 0.77076876, 0.58906984,
        0.64836025, 0.3915379 , 0.36647332, 0.09140646, 0.9623364 ],
       [0.00426507, 0.17026079, 0.6252208 , 0.43848753, 0.4433025 ,
        0.38772285, 0.07178414, 0.5761032 , 0.09315491, 0.79337955],
       [0.80500305, 0.09761369, 0.5921879 , 0.565626  , 0.9552921 ,
        0.13669598, 0.88456726, 0.71196663, 0.5313505 , 0.13599277],
       [0.58390415, 0.01183748, 0.9372722 , 0.03900325, 0.17324603,
        0.1482631 , 0.87750435, 0.46752143, 0.53297806, 0.94097483],
       [0.7745589 , 0.6088046 , 0.9138253 , 0.3655845 , 0.7905592 ,
        0.66924214, 0.5212085 , 0.4094702 , 0.6361649 , 0.46112072],
       [0.92499804, 0.39048326, 0.9970274 , 0.58610344, 0.3691374 ,
        0.8081573 , 0.8941251 , 0.57996285, 0.2831707 , 0.4640082 ],
       [0.63998544, 0.66156745, 0.661768

In [21]:
x = [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9]
out = tf.unique(x)
with tf.Session() as sess:
    print(sess.run(out))

Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9]), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8]))


In [34]:
def loss(x, y):
    avg = tf.reduce_mean(x - y)
    def f1(): return tf.losses.mean_squared_error(y, x)
    def f2(): return tf.reduce_sum(tf.abs(x-y))
    return tf.cond(avg < 0,true_fn=f1, false_fn=f2)

x = tf.random_normal(shape=[300], mean=0, stddev=3)
y = tf.random_normal(shape=[300], mean=0, stddev=3)
out = loss(x, y)
with tf.Session() as sess:
    print(sess.run(out))

1011.2201
